# Generated by Django 4.1.3 on 2023-03-14 13:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Society.upload_img),
        ),
    ]
