python3 manage.py test api.tests.views.test_event.EventTestCase
python3 manage.py test api.tests.views.test_event_info.EventInfoTestCase
python3 manage.py test api.tests.views.test_event_categories.EventCategoriesTestCase
python3 manage.py test api.tests.views.test_event_categories_info.EventCategoriesInfoTestCase
python3 manage.py test api.tests.views.test_event_categories_type.EventCategoriesTypeTestCase
python3 manage.py test api.tests.views.test_event_categories_type_info.EventCategoriesTypeInfoTestCase
python3 manage.py test api.tests.views.test_society_categories.SocietyCategoriesTestCase
python3 manage.py test api.tests.views.test_society_categories_info.SocietyCategoriesInfoTestCase
python3 manage.py test api.tests.views.test_society_categories_type.SocietyCategoriesTypeTestCase
python3 manage.py test api.tests.views.test_society_categories_type_info.SocietyCategoriesTypeInfoTestCase
python3 manage.py test api.tests.views.test_ticket.TicketTestCase
python3 manage.py test api.tests.views.test_ticket_info.TicketInfoTestCase
python3 manage.py test api.tests.views.test_university.UniversityTestCase
python3 manage.py test api.tests.views.test_university_info.UniversityInfoTestCase